In [26]:
import pandas as pd

import numpy as np

from scipy.stats import mode 
import sklearn.datasets as dt

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
import sklearn.metrics as met

In [17]:
df=dt.load_digits()

In [18]:
X=df.data

In [19]:
Y=df.target

In [20]:
kmeans=KMeans(n_clusters=10)

In [21]:
predict=kmeans.fit_predict(X)

In [25]:
labels = np.zeros_like(predict)
for i in range(10):
    mask = (predict==i)
    labels[mask] = mode(Y[mask])[0]

In [30]:
print("Accuracy Score\n\t",met.accuracy_score(Y,labels))


Accuracy Score
	 0.7952142459654981


In [32]:
print("Confusion Matrix::\n",met.confusion_matrix(Y,labels))

Confusion Matrix::
 [[176   0   0   0   2   0   0   0   0   0]
 [  0  55  24   1   0   1   2   0  99   0]
 [  1   2 148  13   0   0   0   3   8   2]
 [  0   0   0 155   0   2   0   7   7  12]
 [  0   3   0   0 166   0   0   8   4   0]
 [  0   0   0   1   2 136   1   0   0  42]
 [  1   1   0   0   0   0 177   0   2   0]
 [  0   0   0   0   0   0   0 176   3   0]
 [  0   6   3   2   0   4   2   5 101  51]
 [  0  20   0   6   0   6   0   7   2 139]]


In [33]:
print("Classification Report::\n",met.classification_report(Y,labels))

Classification Report::
              precision    recall  f1-score   support

          0       0.99      0.99      0.99       178
          1       0.63      0.30      0.41       182
          2       0.85      0.84      0.84       177
          3       0.87      0.85      0.86       183
          4       0.98      0.92      0.95       181
          5       0.91      0.75      0.82       182
          6       0.97      0.98      0.98       181
          7       0.85      0.98      0.91       179
          8       0.45      0.58      0.51       174
          9       0.57      0.77      0.65       180

avg / total       0.81      0.80      0.79      1797

